### ISSUE TITLE
Causing playcover to crash

### ISSUE THREAD

**Issue by Felting** [risporce/Supercell-jailbreak#11]
After extracting app from ipa it cause playcover to crash

**Comment by risporce** [comment]
> After extracting app from ipa it cause playcover to crash

Hi, I would appreciate if you could give a little more detail like is there an error? or exactly when in the installation process does it crashes? or it's just Playcover unable to install the ipa ?
Also which ipa are you using ?

I've seen someone being able to use the Brawl Stars ipa on mac without any issue and I use the exact same patch for all apps.

**Comment by Felting** [comment]
It closes just after it says extracting ipa it switches but I can't read it because it changes too fast

**Comment by sasa8810** [comment]
Play cover doesn’t support tweaked ipa
