### ISSUE TITLE
Clash royale crashing on iOS 14.6

### ISSUE THREAD

**Issue by shahmirk99** [risporce/Supercell-jailbreak#14]
Hi, on my iPhone X 14.6, clash royale crashes after the intro screen. I see the supercell logo, the loading bar says 50% and it crashes

**Comment by shahmirk99** [comment]
Hello, so sorry for replying late! This email was in my spam. I can contact you on either place, but I’ve also attached the crash log in this email. 

1) I did delete the original before installing the patched one, and I installed it using Troll Store on my jailbroken iOS 14.6.

2) To make sure all data is gone from the original app, I deleted your patched app, installed the one from app store, wiped all data with apps manager, then went to the folder and deleted the Clash Royale folder and then redownloaded your ipa.

3) Also tried both with and without “disable tweak injection” for CR through Choicy. 

If you need the crash report from a different app, let me know and I’ll use that (cr4shed doesnt work on my phone, it crashes, ironically enough).

￼


Also a huge thank you for taking the time to reply to the bug report and trying to fix this issue!

**Comment by risporce** [comment]
I can't seem to be able to access your crash logs, both in email and github, it doesn't show the attachment and since you're telling me that all my suggestions didn't work, this is pretty much the last option for me to be able to know what's the crash reason

**Comment by shahmirk99** [comment]
Does this link work? This is the text from the crash log, copy pasted into pastern:

https://pastebin.com/8uYDJmuW￼

**Comment by risporce** [comment]
Perfect, thanks, I've look at it and it's really crashing at trying to load some textures/files it cannot process, but idk the reason as of right now. I can only tell you to try wipe all data with apps manager of the patched app even tho you probably tried already
I've tried to reproduce the bug, I installed CR on my device with TrollStore but I have no issue.

**Comment by moxrow** [comment]
I have very similar problem. Something about resolution not the same/not verified, and also definitely something happening about textures and notes on core foundation 

it was working before, even after I did an iOS update. 
i7, 15.7.8 —> 15.7.9.
I have plenty of free space.

but since I —restorefs, DFU and restore my iOS firmware to stock, this crash is happening now. Never happened before.

Am I missing something important? Clash hasn’t been updated in a couple of weeks from the appstore, but ios dropped minor revisions.

**Comment by moxrow** [comment]
[warning] LogicStringUtil::convertToInt empty String
[warning] read json from file: file not found /var/mobile/Containers/Data/Application/1FAE7811-DC02-4E2A-891F-F58F4D2D0010/Library/Caches/loading/info
[warning] Messaging: expecting ServerHelloMessage during state 3 STATE_HANDSHAKE, received 20103 
[warning] Login failed (error code = 7)

**Comment by risporce** [comment]
> I have very similar problem. Something about resolution not the same/not verified, and also definitely something happening about textures and notes on core foundation
> 
> it was working before, even after I did an iOS update. i7, 15.7.8 —> 15.7.9. I have plenty of free space.
> 
> but since I —restorefs, DFU and restore my iOS firmware to stock, this crash is happening now. Never happened before.
> 
> I even did another Restore, and this time tried clash from the AppStore and it worked, and I removed it. Then, but this ipa still resulted in the same errors. Nothing different.
> 
> Am I missing something important? Clash hasn’t been updated in a couple of weeks from the appstore, but ios dropped minor revisions.
> 
> Edit: I tried the usuals, cache, purge, remove, clean leftovers

I Assume you did re-jailbreak, you will have to first: 
delete all the patched Clash Royale app data with Apps Manager 
then install normal Clash Royale from App Store but never open it, only delete the data also with Apps Manager

Apps Manager also wipe the Keychain data of the app which is very important for Supercell's games so try this and if the error persist send, me full crash log and we'll investigate further

**Comment by risporce** [comment]
> [warning] LogicStringUtil::convertToInt empty String [warning] read json from file: file not found /var/mobile/Containers/Data/Application/1FAE7811-DC02-4E2A-891F-F58F4D2D0010/Library/Caches/loading/info [warning] Messaging: expecting ServerHelloMessage during state 3 STATE_HANDSHAKE, received 20103 [warning] Login failed (error code = 7)
> 
> Edit: new log has this [ERROR] Trying to load too many textures from sc/ui.sc

check issue #15 for a fix

**Comment by moxrow** [comment]
Issue #15 helped me, thanks
