### ISSUE TITLE
My ipad crash on clash royale

### ISSUE THREAD

**Issue by Trix182** [risporce/Supercell-jailbreak#15]
When i enter Clash Royale the game load and at 50 percent the game crash is there anyway that we can talk privately or something?

**Comment by risporce** [comment]
> When i enter Clash Royale the game load and at 50 percent the game crash is there anyway that we can talk privately or something?

If you want to talk privately with me, contact me on discord or telegram, my username on both platform is: risporce
Something you can try is to wipe out the game data with Apps Manager and then try again, if it still crash send me full crash logs and we'll investigate further

**Comment by risporce** [comment]
So i did the test on my side and yes it seems like Clash Royale crash for a stupid reason, looks like they messed up something so here's a temporary fix that worked for me until new Clash Royale update

Before doing the steps, make sure your game still crash and don't wipeout the data if you do:

1. Download this zip file (it's 2 files which is game assets of the game that compose the user interface)
[ui.zip](https://github.com/risporce/Supercell-jailbreak/files/12654145/ui.zip)
2. Open Apps Manager and press the path of Data when you look the info of Clash Royale this will open Filza (install it if you don't have it)
3. Press Clash Royale folder then Documents then Updated then sc
it's at the location indicated in step number 3 that you will have to place the zip file
4. extract it and select the 2 files and press move, go back to sc folder and press paste and replace the files which were there before
you can now delete the ui.zip and ui folder created and open the game, this should work

If you have any problem tell me

**Comment by Trix182** [comment]
Still didn’t work  i tried everything

**Comment by Trix182** [comment]
I will try the second method

**Comment by moxrow** [comment]
Thank you I love you it works

**Comment by risporce** [comment]
newest uploaded ipa of Clash Royale should fix the issue
