### ISSUE TITLE
Brawl stars crashing on startup iOS 12

### ISSUE THREAD

**Issue by bloodyrists** [risporce/Supercell-jailbreak#18]
Hello, I installed it trough sideloadly, yet whenever I want to open the app it crashes immediately.
Am I missing something?

**Comment by bloodyrists** [comment]
Tried Clash Royale and got the same result, here's the error log:


{"app_name":"Clash Royale","timestamp":"2023-10-08 23:47:29.97 +0200","app_version":"3.3314.5","slice_uuid":"fcb59037-e4dc-3149-b404-43c2d580fe4e","adam_id":0,"build_version":"3.3314.5","bundleID":"com.supercell.scroll","share_with_app_devs":false,"is_first_party":false,"bug_type":"109","os_version":"iPhone OS 12.0 (16A366)","incident_id":"05DE0975-50AC-4982-B608-417451485893","name":"Clash Royale"}
Incident Identifier: 05DE0975-50AC-4982-B608-417451485893
CrashReporter Key:   753fe673594c2dbf02284107e386407991001507
Hardware Model:      iPhone11,2
Process:             Clash Royale [1066]
Path:                /private/var/containers/Bundle/Application/2646CF38-AE74-410C-93D0-F27DBA438DC1/Clash Royale.app/Clash Royale
Identifier:          com.supercell.scroll
Version:             3.3314.5 (3.3314.5)
AppStoreTools:       14E221
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           com.supercell.scroll [882]


Date/Time:           2023-10-08 23:47:29.9251 +0200
Launch Time:         2023-10-08 23:47:29.8831 +0200
OS Version:          iPhone OS 12.0 (16A366)
Baseband Version:    1.00.07
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Termination Description: DYLD, Library not loaded: @rpath/libswiftCore.dylib | Referenced from: /var/containers/Bundle/Application/2646CF38-AE74-410C-93D0-F27DBA438DC1/Clash Royale.app/Clash Royale | Reason: image not found
Triggered by Thread:  0

Thread 0 Crashed:
0   dyld                          	0x0000000105910748 0x1058c8000 + 296776
1   dyld                          	0x000000010590fcf8 0x1058c8000 + 294136
2   dyld                          	0x000000010590fd2c 0x1058c8000 + 294188
3   dyld                          	0x00000001058ccb40 0x1058c8000 + 19264
4   dyld                          	0x00000001058cfc0c 0x1058c8000 + 31756
5   dyld                          	0x00000001058c9044 0x1058c8000 + 4164

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000016b89a950   x3: 0x0000000000000094
    x4: 0x000000016b89a550   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x200a656c61796f52  x11: 0x3a6e6f7361655220
   x12: 0x20200a656c61796f  x13: 0x203a6e6f73616552  x14: 0x6f6e206567616d69  x15: 0x00646e756f662074
   x16: 0x0000000000000209  x17: 0x0000000000000001  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016b89a550  x21: 0x0000000000000094  x22: 0x000000016b89a950  x23: 0x0000000000000001
   x24: 0x0000000000000006  x25: 0x00000001059345d0  x26: 0x0000000105933000  x27: 0x0000000105933e30
   x28: 0x0000000105933d70   fp: 0x000000016b89a520   lr: 0x000000010590fcf8
    sp: 0x000000016b89a4e0   pc: 0x0000000105910748 cpsr: 0x00000000

Binary Images:
0x104564000 - 0x1053affff Clash Royale arm64  <fcb59037e4dc3149b40443c2d580fe4e> /var/containers/Bundle/Application/2646CF38-AE74-410C-93D0-F27DBA438DC1/Clash Royale.app/Clash Royale
0x1057f0000 - 0x105847fff HelpshiftX arm64  <06e4cae7bd8838c290f3ff67a590af4e> /var/containers/Bundle/Application/2646CF38-AE74-410C-93D0-F27DBA438DC1/Clash Royale.app/Frameworks/HelpshiftX.framework/HelpshiftX
0x1058c8000 - 0x10592ffff dyld arm64e  <dd964e17241233dfbac7ab6199df95e7> /usr/lib/dyld
0x1059a0000 - 0x1059c3fff Quago arm64  <5d1042bbdbef3db296eece9322b6f6c8> /var/containers/Bundle/Application/2646CF38-AE74-410C-93D0-F27DBA438DC1/Clash Royale.app/Frameworks/Quago.framework/Quago
0x1c08ae000 - 0x1c08affff libSystem.B.dylib arm64e  <6bbce85ee7223439b9e9ebf8a95b5910> /usr/lib/libSystem.B.dylib
0x1c08b0000 - 0x1c090dfff libc++.1.dylib arm64e  <8f583bde2ad837ef88ab65c0eacc1a4b> /usr/lib/libc++.1.dylib
0x1c0922000 - 0x1c10a9fff libobjc.A.dylib arm64e  <2c3e39908f1d3a0c886659587752c61d> /usr/lib/libobjc.A.dylib
0x1c1392000 - 0x1c15fafff libicucore.A.dylib arm64e  <5df0fa200102386b8ace17f24c023440> /usr/lib/libicucore.A.dylib
0x1c160d000 - 0x1c1978fff CoreFoundation arm64e  <5a8ee6e97b45355c99c21026cf710b0a> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
0x1c1b2d000 - 0x1c1ca6fff libsqlite3.dylib arm64e  <bb41d32e18983c9890b7df74ccef80c4> /usr/lib/libsqlite3.dylib
0x1c1cdc000 - 0x1c20affff CFNetwork arm64e  <b88bb92d1f383fab890fe3cf9b564c02> /System/Library/Frameworks/CFNetwork.framework/CFNetwork
0x1c20b0000 - 0x1c23cefff Foundation arm64e  <d517da6fec983485ba064014775bdced> /System/Library/Frameworks/Foundation.framework/Foundation
0x1c23cf000 - 0x1c24e0fff Security arm64e  <c28e4daadc7f3a65ac165e04cb91e8a6> /System/Library/Frameworks/Security.framework/Security
0x1c24e1000 - 0x1c254efff SystemConfiguration arm64e  <76addd04a1a338d4b8e6494484a7109a> /System/Library/Frameworks/SystemConfiguration.framework/SystemConfiguration
0x1c32f4000 - 0x1c38a2fff CoreGraphics arm64e  <330505f7b859356d9a408c3d05fafc23> /System/Library/Frameworks/CoreGraphics.framework/CoreGraphics
0x1c38af000 - 0x1c395afff Metal arm64e  <8a3b381bde4a3e2c88b803cc4e387378> /System/Library/Frameworks/Metal.framework/Metal
0x1c4299000 - 0x1c45e1fff CoreData arm64e  <e5ba01f78bfb35af8e03732557d4d512> /System/Library/Frameworks/CoreData.framework/CoreData
0x1c45f3000 - 0x1c46d2fff CoreTelephony arm64e  <bce69da9f7d233d68959bca7551d3504> /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
0x1c4a9e000 - 0x1c4aabfff OpenGLES arm64e  <697541299ba83a9c9b16bef2e5891386> /System/Library/Frameworks/OpenGLES.framework/OpenGLES
0x1c4b4a000 - 0x1c4b7afff CoreVideo arm64e  <bf1798d403d0363c87cb0f1940d4ff91> /System/Library/Frameworks/CoreVideo.framework/CoreVideo
0x1c4d19000 - 0x1c4ebafff CoreMedia arm64e  <47c9db8e40d53098873d18394e84aad5> /System/Library/Frameworks/CoreMedia.framework/CoreMedia
0x1c546f000 - 0x1c55c4fff CoreText arm64e  <12a8816148b93485abcaf28ac2f8311c> /System/Library/Frameworks/CoreText.framework/CoreText
0x1c5665000 - 0x1c5c79fff AudioToolbox arm64e  <9b3c05a70142351cb0620bf9556933d6> /System/Library/Frameworks/AudioToolbox.framework/AudioToolbox
0x1c5c7a000 - 0x1c5eb9fff QuartzCore arm64e  <2a37bd6145543d5197e932403a5943f7> /System/Library/Frameworks/QuartzCore.framework/QuartzCore
0x1c77dc000 - 0x1c79fafff AVFoundation arm64e  <7d9f04cfc77736689d832d55395fd34d> /System/Library/Frameworks/AVFoundation.framework/AVFoundation
0x1cbe12000 - 0x1cbe48fff UserNotifications arm64e  <84b3549bbf813a1299ef5a37073e7b3a> /System/Library/Frameworks/UserNotifications.framework/UserNotifications
0x1cbef5000 - 0x1cbef5fff UIKit arm64e  <2d59332d7d843e1c8041cfd7374c0905> /System/Library/Frameworks/UIKit.framework/UIKit
0x1cec05000 - 0x1cec35fff GLKit arm64e  <0a5358e2cf21358fa27bb69be68c8f9b> /System/Library/Frameworks/GLKit.framework/GLKit
0x1d0677000 - 0x1d0888fff Photos arm64e  <38ad8ae17bf13bcb9ddd68c595f0a423> /System/Library/Frameworks/Photos.framework/Photos
0x1d1355000 - 0x1d1850fff WebKit arm64e  <1beaf1e2f8e237de8f2af34599f7b000> /System/Library/Frameworks/WebKit.framework/WebKit
0x1d1ee9000 - 0x1d1eeafff AdSupport arm64e  <ab6bdbbd86f839d1bad7bd000f2aea5a> /System/Library/Frameworks/AdSupport.framework/AdSupport
0x1d2df0000 - 0x1d326efff MediaPlayer arm64e  <9631c5db46da30a2a405470e3ad11397> /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
0x1d5526000 - 0x1d5a27fff PhotosUI arm64e  <2c4c96f9a7e73e0a8ea1292b96f4c282> /System/Library/Frameworks/PhotosUI.framework/PhotosUI
0x1d5b35000 - 0x1d5b6ffff StoreKit arm64e  <b43c34e7edd73ef5ab4ec56684d92125> /System/Library/Frameworks/StoreKit.framework/StoreKit
0x1d5d46000 - 0x1d5d61fff MetalKit arm64e  <9af440b811b432eaba6a32b67646bcfc> /System/Library/Frameworks/MetalKit.framework/MetalKit
0x1d76d3000 - 0x1d77d6fff MessageUI arm64e  <61abbfc87fa734a88e0206bcf89c689a> /System/Library/Frameworks/MessageUI.framework/MessageUI
0x1d92c9000 - 0x1d92f9fff OpenAL arm64e  <952269911b923a7ab4340fe6449b7894> /System/Library/Frameworks/OpenAL.framework/OpenAL
0x1dc38f000 - 0x1dc3e8fff iAd arm64e  <f4f2f4d3cede3d6c984c3cf94a276ada> /System/Library/Frameworks/iAd.framework/iAd
0x1de0d0000 - 0x1de0f8fff ReplayKit arm64e  <c33fbccd765c32e789e5feed9f9181a7> /System/Library/Frameworks/ReplayKit.framework/ReplayKit
0x1df230000 - 0x1df232fff DeviceCheck arm64e  <5acde12a160035c6b05f07738541f820> /System/Library/Frameworks/DeviceCheck.framework/DeviceCheck
0x1e3f31000 - 0x1e3f31fff GameKit arm64e  <b490c1410f153f349fb4d90b2622905b> /System/Library/Frameworks/GameKit.framework/GameKit
0x1ebe3c000 - 0x1ebe47fff AuthenticationServices arm64e  <f9bafeace6ba3fa8a447aeec426a80ec> /System/Library/Frameworks/AuthenticationServices.framework/AuthenticationServices

EOF

**Comment by risporce** [comment]
Interesting, that's an easy fix that I will do next update of the UPAs, basically older devices have some library in /Frameworks. 

What you can do to fix it is to download the real IPAs from App Store, take all the .dylib files you see there and place them in the same directory in the patched IPA. this should fix the crashing problem. 

Thank you for reporting me this issue
