### ISSUE TITLE
Duals aint working

### ISSUE THREAD

**Issue by Trix182** [risporce/Supercell-jailbreak#22]
Hi. Its seems that when i chose the 3rd brawlers in duals it never seems to chose can you update to the fix ?

**Comment by risporce** [comment]
It seems like you still use the first build of V52 update, Brawl Stars released a client update to fix that last week and I also updated the IPA on the main page of the repo to the newest version, it's already available since last week, it will fix the problem you have with duels

> Hi. Its seems that when i chose the 3rd brawlers in duals it never seems to chose can you update to the fix ?
