### ISSUE TITLE
Crash iOS 14.2

### ISSUE THREAD

**Issue by Furret-png** [risporce/Supercell-jailbreak#23]
Brawl Stars, Clash of Clans, and Clash Royale all crash instantly while jailbroken. If I reboot to an unjailbroken state they launch like normal though. Disabling tweak injection with Choicy doesn't work. Is this normal? I can provide Cr4shed logs over discord.

I'm using Taurine by the way.

**Comment by risporce** [comment]
Hi, yeah send me crash logs and I’ll take a look at it, but I really don’t understand why they would crash while in jailbroken state but not when in jailed environment after rebooting

**Comment by Furret-png** [comment]
Me neither :/, where do I find your discord?

**Comment by risporce** [comment]
My username is risporce, you can directly message me my dms are opened

**Comment by byeCl0ud** [comment]
Same thing happened to me, I was on iOS 14.7.1 jailbroken with unc0ver. The crash was caused by tweak Liberty Lite (jb bypass tweak). Uninstalling the tweak resolved this problem. I realized I haven't used Liberty anyway.
