### ISSUE TITLE
Boom beach?

### ISSUE THREAD

**Issue by wewewer123** [risporce/Supercell-jailbreak#25]
Could boom beach also get a jailbreak-detection free ipa?

**Comment by mrvizine** [comment]
I second this please!

**Comment by parazyt75** [comment]
up

**Comment by DJLeleX** [comment]
+1

**Comment by mrvizine** [comment]
I contacted risporce and he will work on adding boom beach. Much thanks to risporce!

**Comment by risporce** [comment]
Boom Beach has been added to the list of games, enjoy !
