### ISSUE TITLE
Update to brawl star issue

### ISSUE THREAD

**Issue by Manan2004** [risporce/Supercell-jailbreak#26]
It seems it does not work on jailbroken device any more
works as long as i am not jailbroken
Ios 14.4 ipad

**Comment by risporce** [comment]
Known issue, I can’t find what cause the crash, I will try again with the optional update next week and hopefully there won’t be that issue.

**Comment by risporce** [comment]
Brawl Stars new optional update today have fixed the crash problem i believe, please try it and tell me news

**Comment by Manan2004** [comment]
Can confirm the latest update fixed the issue
