### ISSUE TITLE
Clash Mini login issue

### ISSUE THREAD

**Issue by lebakasable** [risporce/Supercell-jailbreak#29]
I can't connect to Supercell ID in Clash Mini, the app just crashes.

**Comment by risporce** [comment]
Hello, can you please elaborate a little bit more on exactly what is happening and when ? it's really hard to understand what is happening from such little information. SupercellID is not something i control.

Also, can you please send as an attachment here or contact me on discord/telegram username : risporce the crash logs of the application that you can find in settings > privacy > analytics & improvements > analytics data find the newest one with clash mini name on it

**Comment by lebakasable** [comment]
When I click the "Connect to Supercell ID" button, the game crashes 1 or 2 seconds later. I'll send you the logs.

**Comment by risporce** [comment]
solved (Brawl Stars and Clash Mini) are big apps, they will crash on devices with 1gb ram such as iphone 6, ipad air 1, ipod 6 ...etc
