### ISSUE TITLE
Crash on installing Brawl Stars ipa

### ISSUE THREAD

**Issue by Manan2004** [risporce/Supercell-jailbreak#3]
Filza shows no detail 

![IMG_1DBE65F640F1-1](https://github.com/risporce/Supercell-jailbreak/assets/70255981/934715b0-bc44-480c-882c-7df5ee411e8a)

as well as appinst too
<img width="524" alt="image" src="https://github.com/risporce/Supercell-jailbreak/assets/70255981/a702ecdc-e377-4b7f-a7b1-8afb76d30a1d">

My guess is that this ipa file in not made correctly

**Comment by Manan2004** [comment]
Here is filza crash log -

[text-6F50C2CEB4C8-1.txt](https://github.com/risporce/Supercell-jailbreak/files/11816709/text-6F50C2CEB4C8-1.txt)

**Comment by Manan2004** [comment]
My hunch was correct you just made the ipa wrong format 

Here i have uploaded the file in correct format - 
https://gofile.io/d/uY5885

**Comment by risporce** [comment]
i just checked on my side and you're right, it seems like filza doesn't recognize the zip compression that i used to make this ipa,
this time i only tested installation with sideloadly and there was no issue. I will fix it in the next ipas, thank you for telling it.
