### ISSUE TITLE
Clash Royale 

### ISSUE THREAD

**Issue by Shush131** [risporce/Supercell-jailbreak#31]
The new clash Royale ipa crashes on startup when you install via troll store

**Comment by Shush131** [comment]
Also crashes via sideloadly I’m using iPhone XR 14.7

**Comment by risporce** [comment]
thank you, and sorry about that, i miswrote a single number by only 1 difference than the number i was supposed to write, and for some reason it was not crashing on my device so i still uploaded it thinking it was good, it should be fixed now.
