### ISSUE TITLE
Clash royale 6.256.1 iOS16.3.1

### ISSUE THREAD

**Issue by p999x** [risporce/Supercell-jailbreak#32]
“iPhone 13
Jailbreak: Dopamine 2.0.11” 

Aplication crash when installed with trollstore, the crash log indicates a malformed uleb128 variable. Here’s the log:

Incident Identifier: 74E26B9E-9B69-45C4-B07A-5BE1CDFE4A81
CrashReporter Key:   a1e0bcd8ac581b43d10e7daca795996470810b17
Hardware Model:      iPhone14,5
Process:             Clash Royale [19798]
Path:                /private/var/containers/Bundle/Application/DEEE4F6B-3ECB-4C42-A8CF-537D9F3CAE89/Clash Royale.app/Clash Royale
Identifier:          com.supercell.scroll
Version:             6.256.1 (6.256.1)
AppStoreTools:       15E204
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           com.supercell.scroll [2106]

Date/Time:           2024-03-18 17:11:02.2276 +0100
Launch Time:         2024-03-18 17:11:02.2153 +0100
OS Version:          iPhone OS 16.3.1 (20D67)
Release Type:        User
Baseband Version:    2.40.01
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: DYLD 9 
malformed uleb128

Triggered by Thread:  0

Thread 0 Crashed:
0   dyld                          	       0x1036bfebc __abort_with_payload + 8
1   dyld                          	       0x1036c9674 abort_with_payload_wrapper_internal + 104
2   dyld                          	       0x1036c96a8 abort_with_payload + 16
3   dyld                          	       0x10366d6b4 dyld4::halt(char const*) + 328
4   dyld                          	       0x10366b92c dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 4092
5   dyld                          	       0x1036698d4 start + 2388

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000009   x2: 0x000000016da0b4a0   x3: 0x0000000000000014
    x4: 0x000000016da0b0a0   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x000000016da09ecf
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x0000000000000001  x11: 0x000000000000000a
   x12: 0x0000000000000000  x13: 0x0000000000000031  x14: 0x0000000000037fec  x15: 0x000000016da0a1e8
   x16: 0x0000000000000209  x17: 0x00000001036bc7bc  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016da0b0a0  x21: 0x0000000000000014  x22: 0x000000016da0b4a0  x23: 0x0000000000000009
   x24: 0x0000000000000006  x25: 0x000000016da0f4f8  x26: 0x0000000000000000  x27: 0x0000000103557be8
   x28: 0x00000001036e0000   fp: 0x000000016da0b070   lr: 0x00000001036c9674
    sp: 0x000000016da0b030   pc: 0x00000001036bfebc cpsr: 0x40001000
   far: 0x00000001035d4000  esr: 0x56000080  Address size fault

Binary Images:
       0x103654000 -        0x1036d7fff dyld arm64e  <444f50414d494e45444f50414d494e45> /usr/lib/dyld

EOF

**Comment by risporce** [comment]
thank you, and sorry about that, i miswrote a single number by only 1 difference than the number i was supposed to write, and for some reason it was not crashing on my device so i still uploaded it thinking it was good, it should be fixed now.

**Comment by p999x** [comment]
confirmed to be working now, and don't worry, thank you for your work I really appreciate it
