### ISSUE TITLE
CoC constant crash

### ISSUE THREAD

**Issue by Gabe3655** [risporce/Supercell-jailbreak#33]
Worked fine at start then i went to builders base. If it works for others it might be that I didn't play before they split builders base into 2 and now I'm stuck in infinite crash when launching since it launches builders base first. Have tried reinstalling but it keeps in memory that I was builders base last and just crashes.

**Comment by risporce** [comment]
Hi, sorry for the long wait of my answer, I was very busy. You should report to the clash of clans team (in the support section) your issue and explain them exactly what you told me. I am not a developer at Supercell and this is out of my power.
