### ISSUE TITLE
Just a Request, MacOS Window Fix

### ISSUE THREAD

**Issue by SnowKitten248** [risporce/Supercell-jailbreak#34]
Not an Issue more of a Request.

can you add these lines:

<key>UISupportsTrueScreenSizeOnMac</key>
<true/>

To the Info.plist files, when you update the ipa file or include them in the info.plist on the device you extract the files from. So that the app will appropriately scale on Apple Silicon Macs.

Im kinda sick of having to rename the .ipa to .zip extract it modify the info.plist then re-compress the payload before sideloading. Just a suggestion I don't believe it will impact use on iOS or iPadOS devices, However, for some reason this latest version broke zooming on Mac for Clash of Clans. Also, you probably shouldn't include these lines on portrait apps, namely Clash Royale, It used to bug out the UI frequently IDK if this is fixed but it's best not to risk it if you can't test.

**Comment by risporce** [comment]
Alright, I will add this in the next update of these games, I don’t really know how gaming on macOS with supercell IPAs goes, I’ve heard some people say the IPAs don’t work, some other say they work, I don’t have a Mac, but yeah for sure, I’ll try to think about it for the future, thank you for your suggestion. If I forget, tell me ;)

**Comment by risporce** [comment]
i've added it in the newest ipa, i don't know if i did correctly, didn't really had any time to research how to properly add it, tell me if it works

**Comment by SnowKitten248** [comment]
Because your app file is unencrypted, it can be installed through the service SIdeloadly. 
You did not correctly implement this. however, I think this is partially due to a formatting issue with my post caused by GitHub you need to include:

Clash of Clans Info.plist:

//Code
(key)UISupportedInterfaceOrientations(/key)
	(array)
		(string)UIInterfaceOrientationLandscapeRight(/string)
		(string)UIInterfaceOrientationLandscapeLeft(/string)
	(/array)
(key)UISupportsTrueScreenSizeOnMac(/key)
(true/)
//End code

what is above is what the code would look like after "UISupportedInterfaceOrientations" Notice how the array is imbedded as values for this key
"UISupportsTrueScreenSizeOnMac" is a separate key not nested within "UISupportedInterfaceOrientations"  and its value should be "true/" 

Every '<' is replaced with '(' and every '>' is replaced with ')' so that GitHub doesn't remove the formatting.

**Comment by risporce** [comment]
alright thank you for your explanation, i will fix that next time.
