### ISSUE TITLE
*Not Serious* Clash of Clans app launch issue

### ISSUE THREAD

**Issue by itsjohnnyongithub** [risporce/Supercell-jailbreak#37]
Hi. After latest clash of clans update to 16.253, the app tends to have issues opening. Almost every time I launch the app, it takes two or three attempts to launch without immediately closing. I can still play, but this is the first version of the game where I'm having this problem. I can send crashreporter logs if you think this might help? Since I can still access the app, it's not a huge issue. 😅

Thanks.

**Comment by risporce** [comment]
Hello, that’s a very interesting issue, I personally don’t have this crash on both of my phones, I suspect it might be clash of clans itself having an issue, but yes, please send crash logs, maybe the problem is on my side and if it is, I’ll have to fix it, I understand it can be annoying.

**Comment by itsjohnnyongithub** [comment]
Hi this is the CrashReporter log from my most recent crash today. If you need some other type of crash log I will try to provide. https://pastebin.com/FW5EXnv8

**Comment by risporce** [comment]
That’s not the first time I see that, it is most likely caused by one of your tweaks, I never found which does that,  you should try to disable tweak injection in for the game

**Comment by DJLeleX** [comment]
> Hi. After latest clash of clans update to 16.253, the app tends to have issues opening. Almost every time I launch the app, it takes two or three attempts to launch without immediately closing. I can still play, but this is the first version of the game where I'm having this problem. 

I have the same issue, but it's not a big deal..
Another problem I encountered was during the ice cube event, whenever i collected ice cubes and move to the builder base the game would crash, but that not a huge issue, I just wanted to mention it.

**Comment by risporce** [comment]
That's really weird, that's probably a bug with Clash of Clans itself, i only fix the jailbreak detection part, i don't touch a single byte of code.
