### ISSUE TITLE
Brawl Stars crash on launch 55.211

### ISSUE THREAD

**Issue by Vercixx** [risporce/Supercell-jailbreak#38]
Using sideloadly to sideload

**Comment by Manan2004** [comment]
Use trollstore. only that will work

here - https://github.com/opa334/TrollStore

**Comment by risporce** [comment]
That's normal, i didn't upload the new one yet

something changed and suddenly my script that i haven't touched for 1 year suddenly broke, it will take longer than usual, sorry

with the change Brawl Stars did, it will forever be longer with Brawl Stars update

The ipa willl be upload as soon as possible
