### ISSUE TITLE
Squad busters crashing on ios 14.4 ipad pro 12.9 gen 3

### ISSUE THREAD

**Issue by Manan2004** [risporce/Supercell-jailbreak#40]
App is crashing at tutorial just when barbarian hits the skeleton
All tweaks are off 
so i dont know if its game issue or crack issue
Here is the crash file 
[text-AE77FF4D2690-1.log](https://github.com/risporce/Supercell-jailbreak/files/15089936/text-AE77FF4D2690-1.log)

**Comment by risporce** [comment]
Alright thank you, I’ll take a look at it, I would be surprised if there’s more jailbreak detection in the main binary now, but I guess that’s possible ? Or it’s due to something else, anyway , I’ll see if that’s something I can possibly fix or if it’s squad busters problem

**Comment by risporce** [comment]
hey, i pushed another version, please tell me if this fixed your issue, i am personally not facing the crash so i don't know if it fixed it or not this time, i hope yes, please tell me

**Comment by Manan2004** [comment]
Ok yes i can confirm the issue has been fixed thank you.
