### ISSUE TITLE
Zooming Issue in Clash of Clans

### ISSUE THREAD

**Issue by truegreen123** [risporce/Supercell-jailbreak#45]
Cannot zoom in or out in clash of clans, tried everything, like cmd+shift+plus, cmd+scroll, pinching in and out, nothing works.

Thanks!

**Comment by risporce** [comment]
I am not Clash of Clans developer, and Clash of Clans is not officially made to work on Mac, even if it does launch properly, it's expected to not have all working behaviors, I cannot fix this
