### ISSUE TITLE
"The app is invalid"

### ISSUE THREAD

**Issue by gameboi4784** [risporce/Supercell-jailbreak#50]
I get error "The app is invalid" when attempting to sign Brawl Stars 56.25 with SideStore.

**Comment by risporce** [comment]
it's hard to find a zip compressor that supports every tool, i've tried a few ones, and the one i use right now seems to be the one that supports the most tools to install ipas

what you can do is simply extract and re-compress to zip the ipa using a zip compressor you know work with SideStore or use one of the recommended tools to install the ipa from the repo (TrollStore or Sideloadly)
