### ISSUE TITLE
App Still Crashes

### ISSUE THREAD

**Issue by itzTheMeow** [risporce/Supercell-jailbreak#53]
I installed the IPA and the app still crashes on launch.

I am on an iPad Pro 10.5in, using palera1n on iOS 17.6.1

**Comment by risporce** [comment]
Hi, can you send me the crash logs?

You can find it from Settings > Privacy > Analytics & Improvements > Analytics Data. In there find the crash logs for the app that was crashing and send it me, you can upload as file either here or contact me via Discord or Telegram : risporce

**Comment by itzTheMeow** [comment]
The app is Clash of Clans. Im unable to find anything related to the app in the analytics section.

**Comment by risporce** [comment]
Without that, it's hard for me to understand what could have cause the crash.
So here's a few situations a crash might happen even with this ipa:

- The app has been incorrectly installed/signed/ or has overwritten the original app which was on an higher version (to fix wipe data with Apps Manager for the app, delete the app and then reinstall)

- A tweak is interfering with the app (i often saw Clash of Clans crash with other jailbreak bypass tweaks so disable them all)

- The patch i made is incorrectly applied, but it did not crash for me when I tested it

if possible, use sideloadly to install the IPA

**Comment by itzTheMeow** [comment]
Sideloadly worked, thanks.
