### ISSUE TITLE
Optional Clash of Clans update

### ISSUE THREAD

**Issue by SatoshiHP** [risporce/Supercell-jailbreak#55]
Will you be doing the optional Clash of Clans update? I can't play on the one from 3 days ago since it crashes.

**Comment by andywpt** [comment]
@risporce The update is mandatory after the maintenance. 

![IMG_705A1BA9B994-1](https://github.com/user-attachments/assets/e2b265fe-476d-469b-a36b-fa8c8f7359d4)

**Comment by risporce** [comment]
new version uploaded, thanks for telling me
