### ISSUE TITLE
What you use for patch?

### ISSUE THREAD

**Issue by Leeksov** [risporce/Supercell-jailbreak#61]
I’m want make .deb for this

**Comment by risporce** [comment]
Right now it's just a python script that replicate what would the protector patch in runtime of the app
I don't have a lot of experience with making deb tweaks but of course you could always try
The thing is you will need to patch A LOT MORE things than i do.
If you want to try, contact me on Discord or Telegram : risporce and i could tell you more in details

**Comment by risporce** [comment]
I uploaded the scrip, if you still want to see it
