### ISSUE TITLE
How to install and use it now?

### ISSUE THREAD

**Issue by HarryPD168** [risporce/Supercell-jailbreak#67]

**Comment by Alzentane** [comment]
Use TrollStore

**Comment by risporce** [comment]
You have to use the script now, no IPAs will be uploaded from now on.

follow instructions here starting at the prerequisites  [here](https://github.com/risporce/Supercell-jailbreak?tab=readme-ov-file#script)

If you are stuck at some steps, dm me, tell me which and what have you tried so far so that i will be able to guide you

**Comment by HarryPD168** [comment]
> starting

I don’t know much about the code. Can you provide deb/dylib files so that I can import them into the application?

**Comment by risporce** [comment]
you don't really need to understand anything about the code, all you need to do is follow the instructions in the usage section.

I'm well aware this is hard for a lot of people, many never used a terminal before which is why i'm willing to help and improve next weekend how to use it step by step with pictures, i'm preparing that right now

**Comment by snam11** [comment]
> you don't really need to understand anything about the code, all you need to do is follow the instructions in the usage section.
> 
> I'm well aware this is hard for a lot of people, many never used a terminal before which is why i'm willing to help and improve next weekend how to use it step by step with pictures, i'm preparing that right now

i guess it was an easy task but seems i get stuck at the very first stage...
i've installed python, updated pip, installed frida, but when it comes to machlib there is no way i can make it work.
I've tested on 2 different machines but i get the same error:
pip install machlib                                  
ERROR: Could not find a version that satisfies the requirement machlib (from versions: none)
ERROR: No matching distribution found for machlib

any tips on how to solve this issue?

**Comment by risporce** [comment]
> > you don't really need to understand anything about the code, all you need to do is follow the instructions in the usage section.
> > I'm well aware this is hard for a lot of people, many never used a terminal before which is why i'm willing to help and improve next weekend how to use it step by step with pictures, i'm preparing that right now
> 
> i guess it was an easy task but seems i get stuck at the very first stage... i've installed python, updated pip, installed frida, but when it comes to machlib there is no way i can make it work. I've tested on 2 different machines but i get the same error: pip install machlib ERROR: Could not find a version that satisfies the requirement machlib (from versions: none) ERROR: No matching distribution found for machlib
> 
> any tips on how to solve this issue?

I am so sorry, I made a little typo for the name of it, the package name should be macholib, so pip install macholib, I’ll go fix that right now 

Thank you for telling me about this

**Comment by snam11** [comment]
actually i've fixed the issue by downloading the files from github and installing it manually with:
python3 -m pip install -e pathtodownloadedfolder.

but now i have a different issue.
i've dowloaded latest ipa, renamed to zip, and extracted the .app file.
opened the app file (show package content), extracted the bin from there and placed in the python script folder.
i get this error:
python3 sc_protector_file_parser.py --game "laser"         
Found LC_DYLD_INFO_ONLY at offset at : 0x11c8
Found string table fixing address at: 0x1152f30
Found symbol table start address at: 0x12bc570
Found protector loader at: 0x1300
zsh: segmentation fault  python3 sc_protector_file_parser.py --game "laser"

**Comment by risporce** [comment]
It looks like to have a problem exiting the frida session on your OS. I'll try to look into the issue, can you tell me what Operating System you are using? I only have a windows 11 pc and that's it

**Comment by snam11** [comment]
so my setup is a 2012 imac, on catalina, no windows.
btw the main issue is the supercell apps detecting my phone x as jailbroken (but is not, i just have trollstore).
so since i didn't find a way to fix this false positive detection i'm doomed to fix the app on every update

**Comment by risporce** [comment]
It's possible that the updated version of the protector Supercell is now shipping in their client since a week is now capable of detecting TrollStore even without jailbreak

However, to execute this script, you must have jailbreak, or else it won't work.

**Comment by snam11** [comment]
well, i have 2 iphone x on 16.6, both with trollstore and just one has this weird behaviour with the app crashing, 
btw, what can be the issue?
i mean, i didn't rip the ipa from the phone but i've downloaded from a site.
is the ipa rip mandatory?

**Comment by risporce** [comment]
I believe there's something else you can do, but it's a little more complicated.

Frida-Server needs to be installed in other for the script to gather the necessary information from the protector executing at runtime. But you could try to setup Frida-Gadget in the application, you will also need to change the command to launch the application on your iPhone in the script:
https://frida.re/docs/ios/#without-jailbreak

I am not comfortable with this method i probably won't be able to help you there, but it should work in the end

**Comment by snam11** [comment]
thnx i'll have a look in the afternoon.
sorry for the dumb question:
why is the phone needed since the ipa(s) can be downloaded from internet and files can be extracted from there?
and right after the patch, packed back to ipa and sideloaded to the phone?

**Comment by risporce** [comment]
>  the script to gather the necessary information from the protector executing at runtime
Basically for this reason, in runtime the protector is decrypting the encrypted data used to build back the executable binary, so the script is used to gather the decrypted data and then use the information to rebuild the binary

**Comment by HarryPD168** [comment]
![image](https://github.com/user-attachments/assets/2096a1ad-6733-48b5-9cee-9452e0484fce)

There is no module with this name (macholib.MachO)

**Comment by risporce** [comment]
You need to install it with `pip install macholib`

**Comment by MateriaLembo** [comment]
Can you send me The file on discord on in this comment? I dont have pc

**Comment by Johnsmith927** [comment]
> However, to execute this script, you must have jailbreak, or else it won't work.

I need to run Frida with my phone connected to my computer in order for the script to work? That might be why I'm getting "Segmation Fault: 11"

`[INFO] Found LC_DYLD_INFO_ONLY at offset at : 0x11c8
[INFO] Found string table fixing address at: 0x12a2fb8
[INFO] Found symbol table start address at: 0x13cf730
[INFO] Found protector loader at: 0x12f8
Segmentation fault: 11`
Will it work with 17.0 bootstrap? I'm making the ipa for a group of ppl but only have a 17.0 device with trollstore and bootstrap (I dont have the issue with supercell games they do, they just dont have a mac)
