### ISSUE TITLE
clash royale crash

### ISSUE THREAD

**Issue by erfandmc** [risporce/Supercell-jailbreak#7]
hi there first of all i want to thank you for your efforts toward this issue.
the ipa file you provided is not installable with any methods and it crashes whenever i try to install it using filza or Extender.
![IMG_0844](https://github.com/risporce/Supercell-jailbreak/assets/137698016/b333a8fa-2c87-4163-99dd-bafa6dd371ec)

**Comment by risporce** [comment]
hi, thank you for your report, I am aware of the issue, btw this is an old version of Clash Royale and I will update it to newest after my vacation
