### ISSUE TITLE
Script/instructions for decompiling and compiling ourselves?

### ISSUE THREAD

**Issue by JordanEJ** [risporce/Supercell-jailbreak#8]
Hey there,

It is possible to get source code of the programs/scripts that you use to edit the .ipa files so that we can do it ourselves? (and some instructions if possible)

**Comment by risporce** [comment]
hi, soon when i will make deb tweak for bypass jailbreak in sc games, it will be open source, but this script for patching ipa will remain close

**Comment by dualra1n** [comment]
> hi, soon when i will make deb tweak for bypass jailbreak in sc games, it will be open source, but this script for patching ipa will remain close

hello, could you tell me if this avoid the jailbreak detection ? i mean clash royale will not crash again if we have jailbreak ? and if yes did you get it patching the binary right ?

**Comment by risporce** [comment]
hi, that's right, this will work whatever the jailbreak you have, the detection is completely removed and yes the main binary was patched

**Comment by edwin170** [comment]
> hi, that's right, this will work whatever the jailbreak you have, the detection is completely removed and yes the main binary was patched

wow that's amazing, good path bro
