### ISSUE TITLE
IPA install failed

### ISSUE THREAD

**Issue by Alastor822** [risporce/Supercell-jailbreak#85]
Error 180 in Trollstore when try install Brawl Stars

**Comment by vaniademianov** [comment]
where did you get the ipa?

**Comment by risporce** [comment]
Hi, this probably means that the binary is encrypted, you must use a tool that can statistically decrypt the ipa without opening the app like IGameGod or use download a decrypted ipa from a site like armconverter or decrypt.day and try again this script.
