### ISSUE TITLE
I can’t do it

### ISSUE THREAD

**Issue by Alzentane** [risporce/Supercell-jailbreak#87]
I tried for four hours and read all the problems and there was a problem that made me delete jailbreak because frida now i have to download all tweaks again 
If there video tutorial that will be good

**Comment by HarryPD168** [comment]
Can someone share the modified installation package?

**Comment by Alzentane** [comment]
In terminal 
Frida-ps -U 
Then i connect my iPhone 
My phone just restarted 
Even i try to enable jailbreak again it wont just stays in black screen then i have to hard reset

**Comment by Alzentane** [comment]
C:\Users\MyMSI\Desktop\SUPERCELL\Supercell-jailbreak-main\Payload\Squad.app>sc_protector_file_parser.py --game "squad" 
False 
[INFO] Found LC_DYLD_INFO_ONLY at offset at : 0x11c8 
[INFO] Found string table fixing address at: 0xcb4908 
[INFO] Found symbol table start address at: 0xd7a760 
[INFO] Found protector loader at: 0x1300 
Traceback (most recent call last): 
  File "C:\Users\MyMSI\Desktop\SUPERCELL\Supercell-jailbreak-main\Payload\Squad.app\sc_protector_file_parser.py", line 455, in <module> 
    main(game, is_using_mac) 
  File "C:\Users\MyMSI\Desktop\SUPERCELL\Supercell-jailbreak-main\Payload\Squad.app\sc_protector_file_parser.py", line 311, in main 
    pid = device.spawn([f"com.supercell.{game}"]) 
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
  File "C:\Users\MyMSI\AppData\Roaming\Python\Python312\site-packages\frida\core.py", line 86, in wrapper 
    return f(*args, **kwargs) 
           ^^^^^^^^^^^^^^^^^^ 
  File "C:\Users\MyMSI\AppData\Roaming\Python\Python312\site-packages\frida\core.py", line 1029, in spawn 
    return self._impl.spawn(program, **kwargs) 
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
frida.NotSupportedError: unable to launch iOS app via FBS: The operation couldn’t be completed. Application info provider (FBSApplicationLibrary) returned nil for "com.supercell.None"

**Comment by risporce** [comment]
You almost did it correctly, but the case sensitive is important, you must write "Squad” and not “squad”

**Comment by Alzentane** [comment]
C:\Users\MyMSI\Desktop\SUPERCELL\Supercell-jailbreak-main\Payload\Squad.app>python sc_protector_file_parser.py --game "Squad" 
False 
[INFO] Found LC_DYLD_INFO_ONLY at offset at : 0x11c8 
[INFO] Found string table fixing address at: 0xcb4908 
[INFO] Found symbol table start address at: 0xd7a760 
[INFO] Found protector loader at: 0x1300 
Traceback (most recent call last): 
  File "C:\Users\MyMSI\Desktop\SUPERCELL\Supercell-jailbreak-main\Payload\Squad.app\sc_protector_file_parser.py", line 455, in <module> 
    main(game, is_using_mac) 
  File "C:\Users\MyMSI\Desktop\SUPERCELL\Supercell-jailbreak-main\Payload\Squad.app\sc_protector_file_parser.py", line 314, in main 
    session = device.attach(pid) # the address of protectorBase.add(0x0) can change any new build of protector supercell is shipping in their client, at this moment it's 0x429728 
              ^^^^^^^^^^^^^^^^^^ 
  File "C:\Users\MyMSI\AppData\Roaming\Python\Python312\site-packages\frida\core.py", line 86, in wrapper 
    return f(*args, **kwargs) 
           ^^^^^^^^^^^^^^^^^^ 
  File "C:\Users\MyMSI\AppData\Roaming\Python\Python312\site-packages\frida\core.py", line 1071, in attach 
    return Session(self._impl.attach(self._pid_of(target), **kwargs))  # type: ignore 
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
frida.ProcessNotFoundError: target process died unexpectedly

**Comment by risporce** [comment]
Are you on Un0ver jailbreak? 

I am using this jailbreak as well, and this problem happens in Unc0ver 6.2.0 and later, i had to downgrade to Unc0ver 6.1.2 in order for Frida to work properly, I don't know what Un0ver did in order to break Frida in their newer version but this is a workaround if you are using that jailbreak.

**Comment by Alzentane** [comment]
You’re right turaine jailbreak made my phone reset so I downloaded unc0ver 6.2 i will try it again

**Comment by Alzentane** [comment]
C:\Users\MyMSI\Desktop\SUPERCELL\Supercell-jailbreak-main\Payload\Squad.app>python sc_protector_file_parser.py --game "Squad"False
[INFO] Found LC_DYLD_INFO_ONLY at offset at : 0x11c8[INFO] Found string table fixing address at: 0xcb4908
[INFO] Found symbol table start address at: 0xd7a760[INFO] Found protector loader at: 0x1300
[INFO] setup done, don't exit, the computer can take up to a minute to exit frida session[INFO] removed protector loader
[INFO] fixed export functions data and size[SUCCESS] finished fixing binary file, you may now exit pressing CTRL+C
[DEBUG] Duration: 0:00:21.350379

**Comment by Alzentane** [comment]
Now i have to zip folder again ?

**Comment by risporce** [comment]
Yes all worked, make sure you zip the Payload folder with the patched executable file, then renamed it to .ipa and install the new IPA

**Comment by Alzentane** [comment]
patched executable ?
Where i get that ?

**Comment by risporce** [comment]
Just zip back the Payload folder to .zip, rename to .ipa and install, should work

**Comment by Alzentane** [comment]
Install error 180

**Comment by risporce** [comment]
Where, what, how , using what?

**Comment by Alzentane** [comment]
Trollstore i think i missing something like encrypted main binary

**Comment by Alzentane** [comment]
I have encrypted binary from iosgodsgame 
What i have to do now ?
Or i have to start over ?

**Comment by risporce** [comment]
Yes if you have an encrypted binary, you need to start over with a decrypted IPA
usually if you download the IPA from their official site (armconverter.com) those are decrypted IPAs not encrypted (usually) so you should be able to make the patching with those.

**Comment by Alzentane** [comment]
One question 
Where i have to put encrypted ipa ?
I don’t understand

**Comment by risporce** [comment]
You should never an encrypted IPA, you can't do anything with it

**Comment by Alzentane** [comment]
I mean encrypted binary

**Comment by risporce** [comment]
Same thing, delete that you can't use it, start fresh with a new ipa which has a decrypted binary

**Comment by Alzentane** [comment]
It work I did it 
Thanks

**Comment by risporce** [comment]
Alright great
